"use client";

///User
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

/// NEW JOB

export const DOCUMENT_UPLOAD_PROGRESS = "DOCUMENT_UPLOAD_PROGRESS";
export const DOCUMENT_UPLOAD_PROGRESS_SET_NUMBER_OF_FILES =
  "DOCUMENT_UPLOAD_PROGRESS_SET_NUMBER_OF_FILES";
export const DOCUMENT_UPLOAD_PROGRESS_SET_CURRENT_FILE =
  "DOCUMENT_UPLOAD_PROGRESS_SET_CURRENT_FILE";
export const CLEAR_PROGRESS = "CLEAR_PROGRESS";

export const SET_SELECTED_FILES = "SET_SELECTED_FILES";
export const DELETE_FILE = "DELETE_FILE";


export const CLIENT_REF = "CLIENT_REF"


export const CLIENT_SEARCH_BAR = "CLIENT_SEARCH_BAR"




export const CLIENT_DATA_INPUT = "CLIENT_DATA_INPUT"
export const CLIENT_DATA_INPUT2 = "CLIENT_DATA_INPUT2"
export const CLIENT_DATA_INPUT3 = "CLIENT_DATA_INPUT3"
export const CLIENT_GOOGLE_ADDRESS = "CLIENT_GOOGLE_ADDRESS"
export const RESET_CLIENT_INFORMATION = "RESET_CLIENT_INFORMATION"


export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT"
export const SET_SELECTED_CLIENT_INFO = "SET_SELECTED_CLIENT_INFO"
export const REMOVE_SELECTED_CLIENT_INFO = "REMOVE_SELECTED_CLIENT_INFO"


