"use client";

///User
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const CLEAR_USER = "CLEAR_USER"

/// NEW JOB

export const DOCUMENT_UPLOAD_PROGRESS = "DOCUMENT_UPLOAD_PROGRESS";
export const DOCUMENT_UPLOAD_PROGRESS_SET_NUMBER_OF_FILES =
  "DOCUMENT_UPLOAD_PROGRESS_SET_NUMBER_OF_FILES";
export const DOCUMENT_UPLOAD_PROGRESS_SET_CURRENT_FILE =
  "DOCUMENT_UPLOAD_PROGRESS_SET_CURRENT_FILE";
export const CLEAR_PROGRESS = "CLEAR_PROGRESS";

export const SET_SELECTED_FILES = "SET_SELECTED_FILES";
export const DELETE_FILE = "DELETE_FILE";


export const CLIENT_REF = "CLIENT_REF"


export const CLIENT_SEARCH_BAR = "CLIENT_SEARCH_BAR"
export const CONTRACTOR_SEARCH_BAR = "CONTRACTOR_SEARCH_BAR"



export const CLIENT_DATA_INPUT = "CLIENT_DATA_INPUT"
export const CLIENT_DATA_INPUT2 = "CLIENT_DATA_INPUT2"
export const CLIENT_DATA_INPUT3 = "CLIENT_DATA_INPUT3"
export const CLIENT_GOOGLE_ADDRESS = "CLIENT_GOOGLE_ADDRESS"
export const RESET_CLIENT_INFORMATION = "RESET_CLIENT_INFORMATION"


export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT"
export const SET_SELECTED_CLIENT_INFO = "SET_SELECTED_CLIENT_INFO"
export const REMOVE_SELECTED_CLIENT_INFO = "REMOVE_SELECTED_CLIENT_INFO"

export const SET_SELECTED_CONTRACTOR = "SET_SELECTED_CONTRACTOR"
export const SET_SELECTED_CONTRACTOR_INFO = "SET_SELECTED_CONTRACTOR_INFO"
export const REMOVE_SELECTED_CONTRACTOR_INFO = "REMOVE_SELECTED_CONTRACTOR_INFO"
export const RESET_CONTRACTOR_INFORMATION = "RESET_CONTRACTOR_INFORMATION"

export const CONTRACTOR_DATA_INPUT = "CONTRACTOR_DATA_INPUT"
export const CONTRACTOR_DATA_INPUT2 = "CONTRACTOR_DATA_INPUT2"
export const CONTRACTOR_DATA_INPUT3 = "CONTRACTOR_DATA_INPUT3"
export const CONTRACTOR_GOOGLE_ADDRESS = "CONTRACTOR_GOOGLE_ADDRESS"


///service address

export const SET_RECIPIENT = "SET_RECIPIENT"
export const ADD_SERVICE_ADDRESS = 'ADD_SERVICE_ADDRESS';
export const UPDATE_SERVICE_ADDRESS = 'UPDATE_SERVICE_ADDRESS';
export const DELETE_SERVICE_ADDRESS = 'DELETE_SERVICE_ADDRESS';


export const SET_CASE_NUMBER = "SET_CASE_NUMBER"
export const SET_DEF = 'SET_DEF';
export const SET_PLANT = 'SET_PLANT';
export const SET_COURT_NAME = 'SET_COURT_NAME';
export const SET_COURT_INFO = 'SET_COURT_INFO';


export const SET_JOB_NOTES = 'SET_JOB_NOTES';



